### PR TITLE
Added deepcell mesmer

### LINKED ISSUE #318: Increase granularity of watershed bypass
Currently, instance segmentation models are accommodated via `--s3seg-opts '--nucleiRegion bypass'`, which bypasses the watershed segmentation step. However, `--s3seg-opts` is applied universally, making it impossible to run probability map generators in parallel with instance segmenters. The current workaround is to do the parallelization by hand:

```
# Steps up to registration are in common
nextflow run labsyspharm/mcmicro --in exemplar-001 --stop-at registration

# Run probability map computation separately
nextflow run labsyspharm/mcmicro --in exemplar-001 --start-at probability-maps --probability-maps unmicst,ilastik

# ...from instance segmentation, which requires watershed bypass
nextflow run labsyspharm/mcmicro --in exemplar-001 --start-at probability-maps --probability-maps mesmer --s3seg-opts '--nucleiRegion bypass'
```

I propose to allow watershed bypass to be specified on a per-module basis. The most straightforward way is to introduce a new configuration setting `bypass`, which will be `true` for instance segmenters and `false` for probability map generators. Taking into account #317, example specs may look as follows:

```
[
  name      : 'unmicst',
  container : 'labsyspharm/unmicst',
  version   : '2.7.0',
  cmd       : 'python /app/unmicstWrapper.py --stackOutput --outputPath .',
  input     : ''
  channel   : '--channel'
  idxBase   : 1
  bypass    : false
]
```

```
[
  name      : 'mesmer',
  container : 'vanvalenlab/deepcell-applications',
  version   : '0.1.0',
  cmd       : 'python /usr/src/app/run_app.py mesmer --output-directory .',
  input     : '--nuclear-image'
  channel   : '--nuclear_channel'
  idxBase   : 0
  bypass    : true
]
```

### PR DESCRIPTION
**Pull request by ArtemSokolov**
-Added a DeepCell Mesmer module
-Added a new `watershed` configuration option for segmentation modules, allowing individual modules to control whether to run watershed (`'yes'`), bypass watershed but still run s3seg (`'bypass'`) or use the module output as-is (`'no'`). The last option is useful for instance segmenters that don't need additional processing from s3seg.
-Simplified automated tests to test one thing at a time

Closes #318

### CODE REVIEW

**Comment by FloWuenne** [comment]
Thanks for implementing this @ArtemSokolov ! 

I am having two separate questions/things. 

The first is a question for the mesmer module. Is it already possible to do whole-cell segementation with an additional image for membrane staining using `--mesmer-opts '--membrane-image test_image.tif --membrane-channel 2' ` or will this not be handled correctly by nextflow ? 


The second one is an issue when trying to run the mesmer module on our cluster via singularity, which I hadn't encountered locally or with another account on the same cluster before:

```
Command executed:

  python /usr/src/app/run_app.py mesmer --squeeze --output-directory . --output-name cell.tif --nuclear-image K-2016-31617-1_Restain_hLI220216_test.tif

Command exit status:
  1

Command output:
  Downloading data from https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz

      8192/96894291 [..............................] - ETA: 2s
     24576/96894291 [..............................] - ETA: 10:38
     57344/96894291 [..............................] - ETA: 9:07
    122880/96894291 [..............................] - ETA: 6:23
    303104/96894291 [..............................] - ETA: 3:27
    614400/96894291 [..............................] - ETA: 2:07
   1236992/96894291 [..............................] - ETA: 1:09
   1253376/96894291 [..............................] - ETA: 1:14
   2514944/96894291 [..............................] - ETA: 39s
   2531328/96894291 [..............................] - ETA: 42s
   4448256/96894291 [>.............................] - ETA: 25s
   4513792/96894291 [>.............................] - ETA: 26s
   7184384/96894291 [=>............................] - ETA: 17s
   7249920/96894291 [=>............................] - ETA: 18s
  10002432/96894291 [==>...........................] - ETA: 13s
  10215424/96894291 [==>...........................] - ETA: 13s
  10919936/96894291 [==>...........................] - ETA: 12s
  13049856/96894291 [===>..........................] - ETA: 10s
  13344768/96894291 [===>..........................] - ETA: 10s
  13918208/96894291 [===>..........................] - ETA: 10s
  15753216/96894291 [===>..........................] - ETA: 9s
  16392192/96894291 [====>.........................] - ETA: 9s

Command error:
  2022-02-23 11:40:36.717427: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
  2022-02-23 11:40:36.717475: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
  /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
    "The `lr` argument is deprecated, use `learning_rate` instead.")
  Traceback (most recent call last):
    File "/usr/src/app/run_app.py", line 165, in <module>
      app = dca.utils.get_app(ARGS.app)
    File "/usr/src/app/deepcell_applications/utils.py", line 44, in get_app
      return app_map[name]['class'](**kwargs)
    File "/usr/local/lib/python3.6/dist-packages/deepcell/applications/mesmer.py", line 218, in __init__
      extract=True, cache_subdir='models'
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 258, in get_file
      urlretrieve(origin, fpath, dl_progress)
    File "/usr/lib/python3.6/urllib/request.py", line 281, in urlretrieve
      tfp.write(block)
  OSError: [Errno 28] No space left on device
```

**Comment by ArtemSokolov** [comment]
Hi @FloWuenne,

1. Can you give me more information about `test_image.tif`? Where is this file coming from? Is it just an external file that you are providing to Mesmer for all input images, or do you expect it to be generated by an upstream module on a per-image basis? Nextflow needs to know where all the input files are coming from, so it can stage them correctly in a work directory. There is some flexibility is routing input and outputs, but for the most part, the MCMICRO workflow makes some assumptions on the number and type of files available at each step.

2. `OSError: [Errno 28] No space left on device`  <-- Looks like the node on the computer cluster did not allocate enough disk space.

**Comment by FloWuenne** [comment]
Hi @ArtemSokolov,

1) In the easiest scenario, this would be the same multi-channel .ome.tif file that we use for the nuclear stain and we would just define the membrane channel I believe. They specify that: "If not passed, an array of zeroes will be used instead." So maybe the default could be that if the user only specifies a channel, it uses the same input file as for the nuclear image?

2) I actually don't think this has to do with my space on the cluster specifically. I tried this again on a completely different cluster today and got the same error message when running mesmer via nextflow vs running just as a `singularity exec` command (which works without problems!). I think this has probably to do with the mesmer container trying to download and put the pre-trained model file somewhere maybe? I can download this pre-trained file without an issue using wget and I can run the same mesmer container in singularity alone without a problem... I will investigate and update here! 

```
Command output:
  Downloading data from https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz
```

**Comment by ArtemSokolov** [comment]
@FloWuenne 

1. If it's the same .ome.tif file and you know its name ahead of time, then explicitly specifying it in `--mesmer-opts '--membrane-image test_image.tif --membrane-channel 2'` should theoretically work, because the file will already be staged by nextflow inside the corresponding working directory. If it's meant to be a dynamic filename that is assigned by an upstream module, then it's a bit more tricky. MCMICRO uses a highly-configurable [worker process](https://github.com/labsyspharm/mcmicro/blob/master/modules/lib/worker.nf) to execute segmentation containers specified by [module configurations](https://github.com/labsyspharm/mcmicro/blob/3967750b3a1e902d664207f95fe10f4ea2eb7f27/config/modules.config#L23-L57). This allows new segmentation modules to be added via config files without touching Nextflow code. However, the main restriction of this is that the worker has to have homogeneous behavior across the different modules, making it difficult to handle special cases in a single module (mesmer in this case). I'll need to think about whether there is a good workaround to allow the worker process feed the same input file in two different places of a command. Alternatively, we could redefine the number and types of inputs expected by all segmentation modules.

2. I responded in the `deepcell-applications` issue referenced above.

**Comment by j4fam** [comment]
Hi @ArtemSokolov 

I am also trying to run the mesmer module on our cluster via singularity but get an error message. The problem seems to regard the mesmer model download. I don't know how to fix this and your feedback/advice is very much appreciated! I could successfully run a segmentation of that particular image using unmicst, so the overall setup seems ok.

Command executed:
/omics/odcf/analysis/OE0565_projects/cassis/apps/nextflow run labsyspharm/mcmicro -profile singularity --in ./220328_Tonsil_forsegmentation --probability-maps mesmer --start-at probability-maps --stop-at quantification

Error message:
N E X T F L O W  ~  version 22.04.4
Launching `[https://github.com/labsyspharm/mcmicro`](https://github.com/labsyspharm/mcmicro%60) [lonely_mcnulty] DSL2 - revision: 2d4f86d443 [master]

executor >  local (1)
[-        ] process > illumination                   -
[-        ] process > registration:ashlar            -
[-        ] process > dearray:coreograph             -
[8f/490e58] process > segmentation:worker (mesmer-1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > segmentation:s3seg             -
[-        ] process > quantification:mcquant         -
[-        ] process > cellstates:worker              -
[-        ] process > viz:roadie:runTask             -
[-        ] process > viz:autominerva                -
Error executing process > 'segmentation:worker (mesmer-1)'

Caused by:
 Process `segmentation:worker (mesmer-1)` terminated with an error exit status (1)

Command executed:

 python /usr/src/app/run_app.py mesmer --squeeze --output-directory . --output-name cell.tif --nuclear-image 220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif

Command exit status:
 1

Command output:
 Downloading data from https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz

Command error:
     self.endheaders(body, encode_chunked=encode_chunked)
   File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
     self.send(msg)
   File "/usr/lib/python3.6/http/client.py", line 980, in send
     self.connect()
   File "/usr/lib/python3.6/http/client.py", line 1434, in connect
     super().connect()
   File "/usr/lib/python3.6/http/client.py", line 952, in connect
     (self.host,self.port), self.timeout, self.source_address)
   File "/usr/lib/python3.6/socket.py", line 724, in create_connection
     raise err
   File "/usr/lib/python3.6/socket.py", line 713, in create_connection
     sock.connect(sa)
 TimeoutError: [Errno 110] Connection timed out

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 258, in get_file
     urlretrieve(origin, fpath, dl_progress)
   File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
     with contextlib.closing(urlopen(url, data)) as fp:
   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
     return opener.open(url, data, timeout)
   File "/usr/lib/python3.6/urllib/request.py", line 526, in open
     response = self._open(req, data)
   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
     '_open', req)
   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
     result = func(*args)
   File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
     context=self._context, check_hostname=self._check_hostname)
   File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
     raise URLError(err)
 urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/src/app/run_app.py", line 165, in <module>
     app = dca.utils.get_app(ARGS.app)
   File "/usr/src/app/deepcell_applications/utils.py", line 44, in get_app
     return app_map[name]['class'](**kwargs)
   File "/usr/local/lib/python3.6/dist-packages/deepcell/applications/mesmer.py", line 218, in __init__
     extract=True, cache_subdir='models'
   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 262, in get_file
     raise Exception(error_msg.format(origin, e.errno, e.reason))
 Exception: URL fetch failure on https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz: None -- [Errno 110] Connection timed out

Many thanks!
~Johanna

**Comment by ArtemSokolov** [comment]
Hi @j4fam,

What happens when you run Mesmer as a standalone Singularity container outside of MCMICRO?

From the directory that contains your `220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif`:
```
singularity exec -C -B "$PWD" -B "$HOME/.keras" docker://vanvalenlab/deepcell-applications:0.3.0 \
  python /usr/src/app/run_app.py mesmer \
    --nuclear-image "$PWD/220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif" \
    --squeeze --output-directory "$PWD" --output-name cellmask.tif
```

**Comment by j4fam** [comment]
Hi @ArtemSokolov 

Many thanks for your reply! When I run the code you suggested, I get the same error message as the one mentioned by ls
FloWuenne:

Downloading data from https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz
16728064/96894291 [====>.........................] - ETA: 42sTraceback (most recent call last):
  File "/usr/src/app/run_app.py", line 165, in <module>
    app = dca.utils.get_app(ARGS.app)
  File "/usr/src/app/deepcell_applications/utils.py", line 44, in get_app
    return app_map[name]['class'](**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deepcell/applications/mesmer.py", line 218, in __init__
    extract=True, cache_subdir='models'
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 258, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/usr/lib/python3.6/urllib/request.py", line 281, in urlretrieve
    tfp.write(block)
OSError: [Errno 28] No space left on device

I then tried to follow your advice posted here (https://github.com/vanvalenlab/deepcell-applications/issues/16):
1. I created a custom.config file with the following line:
cat /omics/odcf/analysis/OE0565_projects/cassis/apps/custom.config
singularity.runOptions = '-C --nv -B "$HOME"'

2. I included the -c flag in the command:
/omics/odcf/analysis/OE0565_projects/cassis/apps/nextflow run labsyspharm/mcmicro -profile singularity --in ./220328_Tonsil_forsegmentation --probability-maps mesmer --start-at probability-maps --stop-at quantification -c /omics/odcf/analysis/OE0565_projects/cassis/apps/custom.config

But I get the initial error again.

 Traceback (most recent call last):
   File "/usr/src/app/run_app.py", line 165, in <module>
     app = dca.utils.get_app(ARGS.app)
   File "/usr/src/app/deepcell_applications/utils.py", line 44, in get_app
     return app_map[name]['class'](**kwargs)
   File "/usr/local/lib/python3.6/dist-packages/deepcell/applications/mesmer.py", line 218, in __init__
     extract=True, cache_subdir='models'
   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 262, in get_file
     raise Exception(error_msg.format(origin, e.errno, e.reason))
 Exception: URL fetch failure on https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz: None -- [Errno 110] Connection timed out

Any idea what may be the problem and how to work around? Many thanks!
~Johanna

**Comment by ArtemSokolov** [comment]
Hi @j4fam,

It's a little puzzling that you are getting different errors depending on whether you are running Mesmer within MCMICRO or as a standalone container. My suggestion would be to first get Mesmer running by itself, because there is no reason to expect that a container will work inside MCMICRO if it fails during standalone execution.

Based on my previous experience with Mesmer, my understanding is that it downloads the model during execution and caches it in `$HOME/.keras`. If I remove `-B "$HOME/.keras"` from the command I shared with you above, I can replicate the "No space left on device" issue. The `-B` flag exposes a directory on the host machine to be accessible inside the container. So, without ``-B "$HOME/.keras"`, Mesmer will attempt to download a model to a directory that is not mapped to the host machine, which likely results in the container using temporary storage and running over its allocated quota.

Since the above command doesn't work, the next thing to try would be to run the container interactively and attempt to manually download the model to various locations.

Again, from the directory that contains your `220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif` image:
```
singularity shell -C -B "$PWD" -B "$HOME/.keras" docker://vanvalenlab/deepcell-applications:0.3.0
```
This will start a container interactively and map the current directory (`$PWD`) and `$HOME/.keras` from the host machine to be accessible within the container. From here,

1. Attempt to manually download the model to whatever your `$PWD` was:
```
Singularity> cd "...directory containing 220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif..."
Singularity> curl -f -o test.tar.gz https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz
```

2. Attempt to manually download the model to `$HOME/.keras`:
```
Singularity> cd $HOME/.keras
Singularity> curl -f -o test.tar.gz https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz
```

3. Let Mesmer download the model (presumably also to `$HOME/.keras`) during its execution:
```
Singularity> cd "...directory containing 220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif..."
Singularity> python /usr/src/app/run_app.py mesmer \
    --nuclear-image "$PWD/220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif" \
    --squeeze --output-directory "$PWD" --output-name cellmask.tif
```

If you get "out of disk space" errors in 2, but not 1, then that means that `$HOME/.keras` is not getting mapped correctly.
If you get these errors in 3, but not 1 or 2, then that means that Mesmer is downloading the models to some other directory.

Personally, I think that Mesmer developers should just store the model directly inside the container. The model is 92MB, which is tiny compared to the size of the container, so it seems unnecessary to re-download it during every execution. May be worth making a suggestion in https://github.com/vanvalenlab/deepcell-applications/issues, if you can't get runtime download working.

**Comment by j4fam** [comment]
Hi @ArtemSokolov 
Many thanks for your reply. I tried the steps and 1. and 2. worked without a problem. So I can download the file "MultiplexSegmentation-7.tar.gz" manually, but not through the pipeline. Also, I don't know how I can access the downloaded file while running the pipeline. I am thus following your advice to contact the mesmer team with your suggestion. Let's see :)

**Pull request merged**
