### PR TITLE
Background subtraction module

### PR DESCRIPTION
**Pull request by kbestak**
The module is working and not conflicting with existing modules.

### CODE REVIEW

**Comment by kbestak** [comment]
When running on exemplar-001: "IndexError: Boolean array with size 12 is not long enough for axis 0 with size 24" - this is because the markers.csv has only 12 channels, is there a reason for that? Background subtraction would require that the number of channels in the markers.csv matches the number of channels in the image. (Users should also specify a "background" column with "TRUE" values for autofluorescence channels, as well as an "exposure" column indicating the exposure time for channel acquisition)
EDIT: when changing the markers.csv to contain 24 channels, the module works!

**Comment by ArtemSokolov** [comment]
@kbestak When downloading exemplars via `exemplar.nf`, the number of markers in `markers.csv` should match the number of channels in `raw/`. By default, the script pulls cycles 6-8 for exemplar 1:

https://github.com/labsyspharm/mcmicro/blob/056e96886e365464f6f2b5789b8f317170c23b18/exemplar.nf#L38-L44

which equals 12 channels.

You can pull all 10 cycles with:
```
nextflow run labsyspharm/mcmicro/exemplar.nf --name exemplar-001 --from-cycle 1 --to-cycle 10
```

**Comment by kbestak** [comment]
@ArtemSokolov Thank you! This cleared up my confusion. Were the previous default cycles from 1 to 3 (at ~February this year)? I had cycles 1-3 and 6-8 in the raw folder which is why the registered image had 24 channels. This then shouldn't be any problem for the module.

**Comment by ArtemSokolov** [comment]
Yes, we switched to cycles 6-8 at some point this year, because they contained more interesting markers for downstream processing.

The code looks great! Should be ready to merge as soon as we get all the tests working.

**Pull request merged**
