### PR TITLE
added cypository cytoplasm segmentation

### PR DESCRIPTION
**Pull request by clarenceyapp**

### CODE REVIEW

**Comment by DenisSch** [comment]
@ArtemSokolov Naive state seems to break here. Is this because Ilastik is not run?

**Comment by DenisSch** [comment]
Is this because Ilastik is not run?

**Comment by ArtemSokolov** [comment]
The currently failing test is due to running out of disk space. I will fix it soon™.

**Comment by ArtemSokolov** [comment]
Closes #43

**Pull request merged**
