### PR TITLE
Update quantification to 1.3.3 - see WARNING

### PR DESCRIPTION
**Pull request by DenisSch**
WARNING:
This release changes naming for X and Y coordinates of cellular centroid position and adds column and row representation according to #18

### CODE REVIEW

**Comment by DenisSch** [comment]
@ArtemSokolov Should I or will you update the version on o2? This is still not happening automatic correct?

**Comment by ArtemSokolov** [comment]
I don't know if there is a way to have O2 installation update automatically right now. We are still waiting for RC to add container support, which will simplify and automate a lot of things.

I noticed that you didn't increment `params.mcmicroVersion` to the current date. Were you thinking of just doing `git pull` in the most recent install? It might mess up currently-running processes.

**Comment by DenisSch** [comment]
@ArtemSokolov It was just a mistake, I changed the date now.

**Comment by ArtemSokolov** [comment]
@DenisSch Thanks. Go ahead and update the O2 install with:

```
nextflow pull labsyspharm/mcmicro-nf
nextflow run labsyspharm/mcmicro-nf/setup.nf -profile O2
```

It will be a good exercise. ;)
Let me know if you run into problems.

**Pull request merged**
