### PR TITLE
Change to 1.4.1 for #183

### PR DESCRIPTION
**Pull request by DenisSch**
#183

### CODE REVIEW

**Comment by DenisSch** [comment]
@ArtemSokolov Can you restart the test. I assume the new docker container was not ready when I created this pull request.

**Comment by ArtemSokolov** [comment]
@DenisSch Yea, I restarted it on Sunday. It runs ilastik but fails at the interface between ilastik and s3seg:

https://travis-ci.com/github/labsyspharm/mcmicro/jobs/384032587

**Comment by ArtemSokolov** [comment]
Specifically,

```
Traceback (most recent call last):
    File "/app/S3segmenter.py", line 485, in <module>
      nucleiMask = S3NucleiSegmentationWatershed(nucleiPM,nucleiCrop,args.logSigma,TMAmask,args.nucleiFilter,args.nucleiRegion)
    File "/app/S3segmenter.py", line 177, in S3NucleiSegmentationWatershed
      for prop in P
  ValueError: not enough values to unpack (expected 4, got 0)
```

**Comment by DenisSch** [comment]
@clarenceyapp Do you know what the issue is here?

**Comment by clarenceyapp** [comment]
@DenisSch can i get access to the files so i can reproduce locally? Sometimes I get that error when there are no cells detected, but that's unlikely here.

**Comment by DenisSch** [comment]
I am not sure what the issue is but the model does not work after it's dockerized. Just uploaded a new version and triggered a new release.

**Pull request closed without merging**
