### PR TITLE
Update coreograph version in modules.config

### PR DESCRIPTION
**Pull request by clarenceyapp**

### CODE REVIEW

**Comment by clarenceyapp** [comment]
not sure why git actions is failing. It was working with coreograph:2.2.2. There was a release for 2.2.3 that didn't get incorporated into MCMICRO (Testing auto-building of Docker container images). 2.2.4 complains about the opencv module missing a file, but there were no changes made to that.

**Comment by clarenceyapp** [comment]
@ArtemSokolov can you take a look at this? V2.2.2 worked and was the last version to be incorporated into MCMICRO. V2.2.3 includes the new dockerhub.yml file for autobuilding. When the docker container is tested locally, there is an error despite no changes to dependencies and the Dockerfile. 

`  File "UNetCoreograph.py", line 10, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

It didn't actually get merged into MCMICRO so we didn't encounter this error. V2.2.4, which now has tissue splitting, also doesn't work because of the same error. Could there be an issue with dockerhub.yml?

**Comment by ArtemSokolov** [comment]
Looks like it was an issue with [static library](https://github.com/HMS-IDAC/UNetCoreograph/blob/3902c586194abd0c61566fa5ac00b45d6255b387/Dockerfile#L3) dependencies. A recent update to one of them must have dropped `libGL.so` from the dependencies somewhere. There are some [recent reports](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo/66473309#comment123588411_63377623) that `ffmpeg libsm6 libxext6` is no longer sufficient.

I switched to a different dependency specification in https://github.com/HMS-IDAC/UNetCoreograph/pull/6. It's supposed to be more robust, but unfortunately it grew the Docker image size by ~25%. It's possible that this may trigger "out of disk space" errors during the test, so we may need to break up https://github.com/labsyspharm/mcmicro/blob/9e4edc708f86e27c823fc00dbee08877e4787a99/.github/workflows/ci.yml#L177 into doing registration, dearraying and segmentation in three separate steps and removing corresponding Docker images in-between each step.

If there are no disk space issues and the tests finish successfully, feel free to merge.

**Comment by clarenceyapp** [comment]
@ArtemSokolov Looks great, thanks for merging.

**Pull request merged**
