### PR TITLE
Denis sch patch quantification 1.2.1

### PR DESCRIPTION
**Pull request by DenisSch**
Add 1.2.1 for backwards compatibility of CSV file format

### CODE REVIEW

**Comment by DenisSch** [comment]
#60

**Comment by ArtemSokolov** [comment]
Thanks, Denis. Going to piggy back on this and bump Coreograph version up to Clarence's latest. Once I do that, I'll merge the PR.

**Comment by ArtemSokolov** [comment]
@DenisSch :

```
  Traceback (most recent call last):
    File "/app/CommandSingleCellExtraction.py", line 11, in <module>
      SingleCellDataExtraction.MultiExtractSingleCells(**args)
    File "/app/SingleCellDataExtraction.py", line 223, in MultiExtractSingleCells
      ExtractSingleCells(mask,image,channel_names,output)
    File "/app/SingleCellDataExtraction.py", line 171, in ExtractSingleCells
      channel_names_loaded_list = list(channel_names_loaded.marker_name)
    File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
      return object.__getattribute__(self, name)
  AttributeError: 'DataFrame' object has no attribute 'marker_name'
```

Local run on exemplar-002 with old `markers.csv`.

**Comment by ArtemSokolov** [comment]
I hijacked 2020-04-09 for pre-installed conda environments and other updates in this PR.

Going to close this to avoid potential unnecessary conflicts in code version.

@DenisSch when quantification works on old and new version of markers.csv, can you please open another PR from the most recent commit?

**Pull request closed without merging**
