### PR TITLE
Backsub - updated version and documentation

### PR DESCRIPTION
**Pull request by kbestak**
Added functionality that any channel can be subtracted.
The `markers.csv` should contain the "marker_name", "background" and "exposure" columns.
The "background" column indicates which channel should be subtracted - it has to match an existing "marker_name" value. If no background subtraction is necessary for the channel, the "background" value for the channel should be empty.
The "exposure" column indicates the exposure times at channel acquisition.
Added optional column "remove" to indicate whether the channel should be excluded from the output image with "TRUE".

### CODE REVIEW

**Comment by ArtemSokolov** [comment]
Thanks, @kbestak.

Looks like the new version is failing one of the tests: https://github.com/labsyspharm/mcmicro/actions/runs/3904114841/jobs/6669500947#step:8:330

Steps to reproduce:
* Pull cycles 1 through 3 of exemplar-001 (which contain autofluorescence channels):
`nextflow exemplar.nf --name exemplar-001 --from-cycle 1 --to-cycle 3`
* Test your new version with:
`nextflow main.nf --in ~/data/exemplar-001 --background`

**Comment by kbestak** [comment]
Hi @ArtemSokolov, thank you for the instructions to reproduce the error.

In the new version I've changed how the user instructs which channels should be subtracted. Previously, it was done with the "TRUE" values in the "background" column of the markers.csv, however, from this version, the "background" column will specify on a channel basis what to subtract. This functionality would let users subtract other channels if needed which would not have been possible in the previous interface. Users can also specify with the "remove" column if they want to exclude certain channels, so the background channels are not automatically removed as was the case previously.
Due to these changes, the markers.csv in the test should be changed accordingly. Here is the markers.csv for the first three cycles which worked on my computer:

channel_number,cycle_number,marker_name,Filter,excitation_wavelength,emission_wavelength,background,exposure,remove
1,1,DNA_1,DAPI,395,431,,100,  
2,1,AF488,FITC,485,525,,100,TRUE
3,1,AF555,Sytox,555,590,,100,TRUE
4,1,AF647,Cy5,640,590,,100,TRUE
5,2,DNA_2,DAPI,395,431,,100, 
6,2,A488_background,FITC,485,525,AF488,100, 
7,2,A555_background,Sytox,555,590,AF555,100, 
8,2,A647_background,Cy5,640,690,AF647,100, 
9,3,DNA_3,DAPI,395,431,,100,
10,3,FDX1,FITC,485,525,AF488,100,
11,3,CD357,Sytox,555,590,AF555,100, 
12,3,CD1D,Cy5,640,690,AF647,100,

Apologies for the complication, but I'm certain this is the better and less restrictive approach in the long run.
Additionally, the exemplar-001 image indicated a different bug which has been fixed in v0.3.1 which is added to the defaults now.

**Comment by ArtemSokolov** [comment]
Thanks, @kbestak. I just updated the source `markers.csv` as you recommended, so future tests should pull the updated version.

Looks like it can't find `v0.3.1` of the container: https://github.com/labsyspharm/mcmicro/actions/runs/3916415286/jobs/6695504590

I'm not seeing it among the tags on https://github.com/schapirolabor/Background_subtraction/pkgs/container/background_subtraction
Did that fail to push to `ghcr.io` by chance?

**Comment by kbestak** [comment]
Thank you, @ArtemSokolov. That seems to have been the case. It is up and running now!

**Pull request merged**
